### ISSUE TITLE
"Are You A Physician / Are You A Coder" Outbound Links

### ISSUE THREAD

**Issue by nthopinion** [nthopinion/covid19#3]

**Comment by nthopinion** [comment]
![image](https://user-images.githubusercontent.com/62161323/76804488-a25ecb00-6799-11ea-92e6-6292632af851.png)

![image](https://user-images.githubusercontent.com/62161323/76804513-b0ace700-6799-11ea-9d20-74e4940cae9d.png)

**Comment by MalaikaAbid** [comment]
Working on this. Let me know of any preferences for styling.

**Comment by nthopinion** [comment]
We're not experts in UI/UX, but someone in the slack was! Let's ask for advice :)...

**Comment by raynman1** [comment]
I will work on the physician page, and instructions page, with the following text: 

**How The App Works: Users**
Our application is a web app. It has a public facing interface, and a doctor/healthcare worker facing interface. Users can search through a database of previously asked questions about COVID-19 (or add their question to the database if it hasn't already been asked), and obtain answers from medical professionals around the globe
Our realtime database will contain the most urgent questions and answers on COVID-19 and publish it to the world. With our app in the hands of front line workers who have or are already experiencing the first wave, they can share their knowledge and help the health care workers who will be hit next. 
The search box will comb through our database to see if your question has already been answered. If it has, the answer will be displayed. If your question hasn't been answered yet, then it will automatically be submitted to physicians around the world. It is important to completely finish writing your question, even though the search bar tries to submit what is being typed in the search box every 3 seconds. It is a bug we are trying to fix, but we will get the entire question on the physician-facing side of the interface. 
Your question will be directed to a physician to answer. Your question and the corresponding answer will then automatically be added to the database so others can see it. The question and it's answer will be published once the physician submits his/her answer. 
If you would like to report an issue with any of the questions or answers, simply select the red flag button and we will be notified.

**How Our Apps Work: Medical Professionals**
Medical professionals should create a login and password.  It is possible to use your Google account. Note this has been a major stumbling block and friction for physicians.  It is recommended that you save your passwords on your phone which will make it easier. This is currently undergoing major improvements and should improve over time. 
You can change from “unanswered questions” to “answered questions” by clicking the button. “Answered questions” is public-facing and your answer to a question will be published the moment you submit your answer.  You can edit your answers by clicking on the button labelled "Answered questions”.  You are able to delete a question but please be judicious as you will notice there may be many duplicates due to the current entry mechanism. We ask that you keep answers on the database because deleting the answer will result in deleting the answer for the entire world. Please leave all non-duplicate questions, so other physicians can answer them. The questions are stored in a single database and all physicians see the same questions.
There are known bugs and issues with the interface.  If you see a question but there's no field to answer the question, please refresh your screen (CTRL + R) and the blank field to type your answer will appear. We are working hard on fixing this. 

**Hackathon Instructions: Coders**
Bug reports
Manage, organize, prioritize Github
Lead an open source project
Create and submit Issues

Currently we are working on a continuous integration and continuous development workflow.  Our team leader is Jay and we will add you to our public Slack for rapid onboarding.  He will onboard you from there.  

https://join.slack.com/t/hackingcovid19/shared_invite/zt-cs0oy49c-bwn5uoilSme1iqFDDK7~zg

**Doctors, Providers, Translators**
Doctors: please login and help answer vital questions as you see fit.  Please only answer questions that you can answer with certainty.  We will have our team of physicians review your answers as time allows.  Use the “Answered questions” button to see what your answer will look like to the public. Please submit requests for any additional functions you identify, and please report issues. We will use your feedback to stimulate discussion, challenge our coders, and push the limits of web and AI technology. Let’s have fun at the same time. For doctors that speak different languages, please try to use English -- but if you must use your native language, that is good too and we will have other translators add a second script in the same answer box.

**Feature Requests** 
Please send us an email to suggest additional functions for the platform.  We will try to have a coder in the community add it for you ASAP. They are volunteers, and so we will prioritize depending on the front line needs of health care workers and patients.

**Comment by aviskarkc10** [comment]
this has been implemented
